### ISSUE TITLE
Previous inventory site

### ISSUE THREAD

**Issue by jas-** [garinrk/lib_inventory#1]
Hey, I just saw this pop up on my feed.

You know Seth & I worked on a project to track assets a few years ago. Maybe the code base could help.

[Server RESTful API](https://github.com/jas-/MLIB-Inventory-Server)
[Web Client](https://github.com/jas-/MLIB-Inventory)

Set did the mobile components. Let me know if it does.

**Comment by garinrk** [comment]
Oh cool! Thanks, this was a final project for my databases course haha. Just was making a few things public but I'll definitely check these out if I revisit it :)

**Comment by jas-** [comment]
No worries, the name led me to believe Jeff was doing a rewrite and thought it might help
